uglifyjs.cmd js/platform.js > uglify/platform.min.js
uglifyjs.cmd js/ios_fullscreen.js > uglify/ios_fullscreen.min.js
uglifyjs.cmd js/screenfull.js > uglify/screenfull.min.js
uglifyjs.cmd js/ctl_utils.js > uglify/ctl_utils.min.js
uglifyjs.cmd js/sprite_lib.js > uglify/sprite_lib.min.js
uglifyjs.cmd js/settings.js > uglify/settings.min.js
uglifyjs.cmd js/CPreloader.js > uglify/CPreloader.min.js
uglifyjs.cmd js/CMain.js > uglify/CMain.min.js
uglifyjs.cmd js/CTextButton.js > uglify/CTextButton.min.js
uglifyjs.cmd js/CGfxButton.js > uglify/CGfxButton.min.js
uglifyjs.cmd js/CToggle.js > uglify/CToggle.min.js
uglifyjs.cmd js/CMenu.js > uglify/CMenu.min.js
uglifyjs.cmd js/CGame.js > uglify/CGame.min.js
uglifyjs.cmd js/CInterface.js > uglify/CInterface.min.js
uglifyjs.cmd js/CTweenController.js > uglify/CTweenController.min.js
uglifyjs.cmd js/CSeat.js > uglify/CSeat.min.js
uglifyjs.cmd js/CFichesController.js > uglify/CFichesController.min.js
uglifyjs.cmd js/CVector2.js > uglify/CVector2.min.js
uglifyjs.cmd js/CGameSettings.js > uglify/CGameSettings.min.js
uglifyjs.cmd js/CEasing.js > uglify/CEasing.min.js
uglifyjs.cmd js/CHandController.js > uglify/CHandController.min.js
uglifyjs.cmd js/CCard.js > uglify/CCard.min.js
uglifyjs.cmd js/CInsurancePanel.js > uglify/CInsurancePanel.min.js
uglifyjs.cmd js/CGameOver.js > uglify/CGameOver.min.js
uglifyjs.cmd js/CConnectWallet.js > uglify/CConnectWallet.min.js
uglifyjs.cmd js/CMsgBox.js > uglify/CMsgBox.min.js
uglifyjs.cmd js/CCreditsPanel.js > uglify/CCreditsPanel.min.js
uglifyjs.cmd js/CFiche.js > uglify/CFiche.min.js
uglifyjs.cmd js/CCTLText.js > uglify/CCTLText.min.js